apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: cimagens-mongodb
  name: cimagens-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: cimagens-mongodb
    spec:
      containers:
      - image: mongo:4.0.13
        name: cimagens-mongodb
        ports:
        - containerPort: 27017
        resources: {}
