apiVersion: v1
kind: Service
metadata:
  labels:
    service: cimagens-mongodb
  name: cimagens-mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: cimagens-mongodb

