version: '2'
services:
    cimagens-app:
        image: cimagens
        #environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
    jhtst-mongodb:
        image: mongo:4.0.13
        ports:
          - '27017:27017'
        # volumes:
        #     - ~/volumes/cimagens/mongodb/:/data/db/
